### ISSUE TITLE
The Secondary Utility Menu Page - side menu doesn't work.

### ISSUE THREAD

**Issue by michael-milette** [wet-boew/wet-boew-php#171]
The Secondary Utility Menu Page - side menu - doesn't work in the demos-php site. The following error message appears in its place:

    Warning: include(/var/www/wet-boew-phpdist-php/menu/menu-util.php): failed to open stream: No such file or directory in /var/www/wet-boew-php/demos-php/pages/menu-left-gauche/left-menu-util-demo.php on line 4

    Warning: include(): Failed opening '/var/www/wet-boew-phpdist-php/menu/menu-util.php' for inclusion in /var/www/wet-boew-php/demos-php/pages/menu-left-gauche/left-menu-util-demo.php on line 4

    Fatal error: Call to undefined function buildLeftMenu() in /var/www/wet-boew-php/demos-php/pages/menu-left-gauche/left-menu-util-demo.php on line 13

While I can fix the missing slash between wet-boew-phpdist-php in the first error, the menu-util.php file is missing. I suspect that the missing buildLeftMenu() function is suppose to be included in the menu-util.php file.

**Comment by upsonp** [comment]
The buildLeftMenu() function is in the menu-util.php file (https://github.com/wet-boew/wet-boew-php/blob/v4.0/dist-php/menu/menu-util.php)

**Comment by michael-milette** [comment]
Got it, thanks! I'll send you the fix for the paths.

**Comment by michael-milette** [comment]
Thanks @upsonp! Works perfectly.
