### ISSUE TITLE
Title is just a slash on language selection splash page of on demos-php

### ISSUE THREAD

**Issue by michael-milette** [wet-boew/wet-boew-php#173]
WHAT IT IS

![image](https://cloud.githubusercontent.com/assets/3808579/11640962/88f5e456-9d03-11e5-887a-53f496a3fe05.png)

WHAT IT SHOULD BE (according to WET-BOEW HTML dist)

![image](https://cloud.githubusercontent.com/assets/3808579/11641012/dbbc2a24-9d03-11e5-93da-f78d8c39e559.png)

**Comment by upsonp** [comment]
For multi-lingual pages you have to set

```php
$_PAGE['title_en'] = "Language selection";
$_PAGE['title_fr'] = "Sélection de la langue";
$_PAGE['sub_title_en'] = "Government of Canada Web Usability Theme - Web Experience Toolkit";
$_PAGE['sub_title_fr'] = "Thème de la facilité d’emploi Web du gouvernement du Canada - Boîte à outils de l’expérience Web";
$_PAGE['lang1'] = "en";
$_PAGE['lang2'] = "fr";
```

If it's a splash page you also have to set <code>$_PAGE['issplash'] = "1";</code>

**Comment by michael-milette** [comment]
I updated the demos-php/pages/index.php file. Here is the current code. The sub_title strings are slightly modified to keep the text generic:

    <?php
    // Always set the page language options first.
    // Set 'lang1' to 'en' for English pages, 'fr' for French pages.

    // Note: We check if $_PAGE['lang1'] and $_PAGE['lang2'] are already set if called from splashpage-en.php and splashpage-fr.php.
    if (!isset($_PAGE['lang1'])) $_PAGE['lang1'] = "en";
    if (!isset($_PAGE['lang2'])) $_PAGE['lang2'] = "fr";

    require_once __DIR__ . "/config/config.php";

    // These are the required variables for this page.
    $_PAGE['title_en'] = "Language selection";
    $_PAGE['title_fr'] = "Sélection de la langue";
    $_PAGE['sub_title_en'] = "Web Experience Toolkit";
    $_PAGE['sub_title_fr'] = "Boîte à outils de l’expérience Web";

    $_PAGE['issplash'] = "1";

    include_once $_SERVER['DOCUMENT_ROOT'] . $_SITE['wb_php_dist_folder'] . "/inc/head-doc.php"; 
    ?>

    
    <meta name="description" content="English description / Description en anglais" />
    <meta name="description" lang="fr" content="French description / Description en français" />
    <meta name="dcterms.creator" content="English name of the content author / Nom en anglais de l'auteur du contenu" />
    <meta name="dcterms.creator" lang="fr" content="French name of the content author / Nom en français de l'auteur du contenu" />
    

    <?php include_once $_SERVER['DOCUMENT_ROOT'] . $_SITE['wb_php_dist_folder'] . "/inc/head-css.php"; ?>
    
    
    <?php include_once $_SERVER['DOCUMENT_ROOT'] . $_SITE['wb_php_dist_folder'] . "/inc/head-nav.php"; ?>
    
    <?php include $_SERVER['DOCUMENT_ROOT'] .$_SITE['wb_website_root'] . "/pages/includes/index.php"; ?>
    
    <?php include $_SERVER['DOCUMENT_ROOT'] . $_SITE['wb_php_dist_folder'] . "/inc/foot-nav.php"; ?>
    
    
    <?php include $_SERVER['DOCUMENT_ROOT'] . $_SITE['wb_php_dist_folder'] . "/inc/foot-end.php"; ?>

While I do get titles now, I also get the title text appearing on the splash pages. This happens with the splash pages for all three themes.

![image](https://cloud.githubusercontent.com/assets/3808579/11661495/2b99094e-9da0-11e5-98c8-9dde80faff70.png)

Also, only the title text is appearing in the tab, not the subtitle text. So, the tab says "Language selection / Sélection de la langue".

Best regards,

Michael

**Comment by upsonp** [comment]
Ok, I see what's going on. They changed the layout of the splash page. It use to be the title went at the top separated by a slash with the subtitles left & right aligned with the leaf in the middle.

I'll have to rework the layout.

**Comment by upsonp** [comment]
I've fixed the splash page layout, but noticed one issue with using a single set of generic pages and the <code>?theme=xxx-theme</code>

If I set the title on the GCWU them, the same title will be used for the other themes. Not a major issue and maybe it could be worked around by having a check in the boilerplate index.php file where the title is set so it's set depending on what theme is being used.
![dif](https://cloud.githubusercontent.com/assets/3355126/11718362/f9dd4f72-9f2b-11e5-94a4-9be995ad93aa.png)

**Comment by michael-milette** [comment]
Hi @upsonp 

The reason you have the wrong name appearing on the splash page is because you hard coded the name of the theme. You should not do this. For the demo site, use the following variable to display the name of the active theme:

    $_SITE['theme_list_' . $_PAGE['lang1']][$_SITE['wb_theme']]

and

    $_SITE['theme_list_' . $_PAGE['lang2']][$_SITE['wb_theme']]

The arrays $_SITE['theme_list_en'] and $_SITE['theme_list_fr'] are defined in the dist-php\config\config-xx.php language files (currently only English (en) and French (fr). I included definitions for all 6 core themes even though we only have 3 available right now.

This will result in the correct theme name to appear depending on which theme is being used. See demos-php/index-en.php for a working example.

As for the alignment issue, we will need to look into that. I could be mistaken but I think we should be able to handle that through customizations to files under dist-php/theme-xxxx/sp-pe. It's only the data files that are common. We still have the ability to customize php code.

I am currently busy developing the WET theme for Moodle using WET-BOEW-PHP however I should have a chance to look at your latest efforts Friday or Monday. Could you merge any changes you have pending by the end of Thursday so that we are working with a common codebase?

Of course we could always cheat and just change the string to make it shorter ;-)

Best regards,

Michael

**Comment by upsonp** [comment]
@michael-milette Thanks, It's done, right title for right themes.

**Comment by michael-milette** [comment]
@upsonp Looks good to me except for the alignment issue however that seems to happen even with the WET-BOEW version if the text is too long for one line. Thanks!

Michael
