### ISSUE TITLE
FIP images missing on 404 server pages in demos-php site

### ISSUE THREAD

**Issue by michael-milette** [wet-boew/wet-boew-php#174]
AS IT IS NOW:

![image](https://cloud.githubusercontent.com/assets/3808579/11658912/77ac9c2c-9d93-11e5-8c58-1be1b0d83eed.png)

AS IT SHOULD BE (according to WET-BOEW dist)

![image](https://cloud.githubusercontent.com/assets/3808579/11658959/bc2681ba-9d93-11e5-809d-1f7a6b58a98c.png)

**Comment by michael-milette** [comment]
Forgot to mention, this is for the gcwu-fegc (and eventually gc-intranet and gcweb) themes. Might also be nice to be able to include a logo if one is defined for the other themes as well.

**Comment by upsonp** [comment]
I'm working on the error page issues you flagged. Looks like there should be theme specific headers. I don't know why the "warning" gliph isn't showing up properly in the GCWU-FEGC theme, but does in the base theme. Maybe there's a character encoding issue with one of the GCWU-FEGC theme files?

**Comment by upsonp** [comment]
I think I found the issue. in the dist-php/inc/err/head.php file <code>$_SITE['wb_core_root']</code> was being used to determine the path to the theme appropate header to use. I changed it to <code>"/".$_SITE['wb_theme']</code> and it seems to work.

Merge incoming.

**Comment by michael-milette** [comment]
Hi @upsonp ,

Just tested your fix. I am now getting the following errors when I go to the demos-php/pages/404-en.php, demos-php/pages/404-en-fr.php and demos-php/pages/404-en-fr.php pages:

    Parse error: syntax error, unexpected ')', expecting ']' in /var/www/wetsite/wet-boew-php/dist-php/theme-base/err/head.php on line 4
    Parse error: syntax error, unexpected ')', expecting ']' in /var/www/wetsite/wet-boew-php/dist-php/theme-base/err/head.php on line 13

Looks like you are missing closing ] and ) brackets in both cases.

Best regards,

Michael

**Comment by upsonp** [comment]
Thanks @michael-milette, It's been taken care of.

**Comment by michael-milette** [comment]
Thanks @upsonp , works perfect!
